import {Container, Stack, Center, StackDivider, Divider} from "@chakra-ui/layout";
import {Button} from "@chakra-ui/react";

import {getAllServicesIds, getServiceData} from "../../lib/services";
import {getUzelData} from "../../lib/uzels";
import Head from "next/head";
import ServiceInfo from "../../components/Services/serviceInfo";

const Service = ({service={}, uzel={}}) => {

    return(
        <>
            <Head>
                <title>{service.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container maxW="container.lg" h={"xl"} mt={16}>

                <Stack
                    direction={["column", "row"]}
                    spacing="6"
                    h={"full"}
                    divider={<StackDivider borderColor="gray.200" />}
                >

                    <ServiceInfo service={service} uzel={uzel}/>
                    <Center h={["3xs", "full"]}>
                        <Button size={"lg"} colorScheme={"orange"}>
                            Записаться
                        </Button>
                    </Center>
                </Stack>
            </Container>

            <Divider/>
        </>
    )
}

export default Service

export async function getStaticPaths() {
    const paths = await getAllServicesIds();
    return {
        paths,
        fallback: false
    }
}

export async function getStaticProps({ params }) {
    const serviceData = await getServiceData(params.id)
    const uzelData = await getUzelData(serviceData.data.uzelID)
    return {
        props: {
            service: serviceData.data,
            uzel: uzelData.data,
        }
    }
}