import Head from "next/head";
import {Container, Divider, Heading} from "@chakra-ui/layout";
import {useRouter} from "next/router";

export default function Appointment() {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Запись на услугу</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container mt={16} mb={4} size={"container.lg"}>
                <Heading>Поздравляем! Вы записаны:</Heading>
                <Heading size={"md"}>{router.query.uzel}</Heading>
                <Heading size={"md"}>{router.query.service}</Heading>
                <Heading size={"md"}>{router.query.brand}</Heading>
                <Heading size={"md"}>{router.query.model}</Heading>
            </Container>
            <Divider/>

        </>
    )
}
//
// export async function getStaticProps() {
//     const serviceData = await getAllServices();
//     const uzelsData = await getAllUzels();
//     const brandsData = await getAllBrands();
//     const modelsData = await getAllModels();
//
//     const services = serviceData.map(service => {return service.params.service;})
//     const uzels = uzelsData.map(uzel => {return uzel.params.uzel;})
//     const brands = brandsData.map(brand => {return brand.params.brand;})
//     const models = modelsData.map(model => {return model.params.model;})
//
//     return {
//         props: {
//             uzels,
//             models,
//             brands,
//             services,
//         },
//     };
// }