import Head from "next/head";
import {Container, Divider, Heading} from "@chakra-ui/layout";
import {useRouter} from "next/router";
import {getAllServices} from "../../lib/services";
import {getAllUzels} from "../../lib/uzels";
import {getAllBrands} from "../../lib/brands";
import {getAllModels} from "../../lib/models";
import AppointmentForm from "../../components/Appointment/form";

export default function Appointment({uzels = [], services = [], brands = [], models = []}) {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Запись на услугу</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container mt={16} mb={4} size={"container.lg"}>
                <Heading>Запись на услугу</Heading>
                <AppointmentForm
                    serviceId={router.query.serviceId}
                    uzels={uzels}
                    services={services}
                    brands={brands}
                    models={models}
                />
            </Container>
            <Divider/>

        </>
    )
}

export async function getStaticProps() {
    const serviceData = await getAllServices();
    const uzelsData = await getAllUzels();
    const brandsData = await getAllBrands();
    const modelsData = await getAllModels();

    const services = serviceData.map(service => {return service.params.service;})
    const uzels = uzelsData.map(uzel => {return uzel.params.uzel;})
    const brands = brandsData.map(brand => {return brand.params.brand;})
    const models = modelsData.map(model => {return model.params.model;})

    return {
        props: {
            uzels,
            models,
            brands,
            services,
        },
        revalidate: 600,
    };
}