// styles and package components
import Head from 'next/head'
import {Divider} from "@chakra-ui/layout";
// custom components
import Jumbotron from "../components/jumbotron";
import ServiceAccordion from "../components/Services";
import Advantages from "../components/advantages";
import Brands from "../components/brands";
import Contacts from "../components/Contacts";
// amplify
import {getAllServices} from "../lib/services";
import {getAllUzels} from "../lib/uzels";
import {getAllAdvantages} from "../lib/advantages";
import {getAllBrands} from "../lib/brands";

export async function getStaticProps() {
    const serviceData = await getAllServices();
    const uzelsData = await getAllUzels();
    const advantagesData = await getAllAdvantages();
    const brandsData = await getAllBrands();

    const services = serviceData.map(service => {return service.params.service;})
    const uzels = uzelsData.map(uzel => {return uzel.params.uzel;})
    const advantages = advantagesData.map(advantage => {return advantage.params.advantage;})
    const brands = brandsData.map(brand => {return brand.params.brand;})

    return {
        props: {
            uzels,
            advantages,
            brands,
            services,
        },
    };
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>JeepService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Jumbotron services={props.services}/>
        <ServiceAccordion uzels={props.uzels} services={props.services}/>
        <Divider/>
        <Advantages advantages={props.advantages}/>
        <Divider/>
        <Brands brands={props.brands}/>
        <Divider/>
        <Contacts/>
        <Divider/>

    </>
  )
}
