// styles and package components
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import {Container, Divider} from "@chakra-ui/layout";
// custom components
import Jumbotron from "../components/jumbotron";
import Header from "../components/Header";
import Services from "../components/Services";
import Advantages from "../components/advantages";
import Brands from "../components/brands";
// amplify
import { Amplify, withSSRContext } from "aws-amplify";
import awsExports from "../src/aws-exports";
import {listUzels, listAdvantages, listBrands} from "../src/graphql/queries";

Amplify.configure({ ...awsExports, ssr: true });

export async function getServerSideProps({ req }) {
    const SSR = withSSRContext({ req });
    const uzelsData = await SSR.API.graphql({ query: listUzels });
    const advantagesData = await SSR.API.graphql({query: listAdvantages });
    const brandsData = await SSR.API.graphql({query: listBrands});

    return {
        props: {
            uzels: uzelsData.data.listUzels.items,
            advantages: advantagesData.data.listAdvantages.items,
            brands: brandsData.data.listBrands.items,
        },
    };
}

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>JeepService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header><Header/></header>
        <main className={styles.main}>
            <Jumbotron/>
            <Services uzels={props.uzels}/>
            <Divider/>
            <Advantages advantages={props.advantages}/>
            <Divider/>
            <Brands brands={props.brands}/>
        </main>
      <footer className={styles.footer}/>
    </div>
  )
}
