import Head from 'next/head'
import styles from '../styles/Home.module.css';
import {Divider, Container} from "@chakra-ui/layout";
import { Amplify, withSSRContext } from "aws-amplify";
import awsExports from "../src/aws-exports";
import {listServices} from "../src/graphql/queries";
import Header from "../components/Header";
import Footer from "../components/Footer";
import ServiceList from "../components/Services/serviceList"
import SearchBar from "../components/searchBar";

Amplify.configure({ ...awsExports, ssr: true });

export async function getServerSideProps({ req }) {
    const SSR = withSSRContext({ req });
    const serviceData = await SSR.API.graphql({query: listServices});

    return {
        props: {
            services: serviceData.data.listServices.items,
        },
    };
}

export default function Services({services = []}) {
    return(
        <div className={styles.container}>
            <Head>
                <title>Service List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Header/>
            </header>

            <main className={styles.main}>
                <Container maxW={"container.lg"} mt={'1rem'}>
                    <SearchBar/>
                    <Divider my={"1rem"}/>
                    <ServiceList services={services} uzelId={'all'}/>
                </Container>
            </main>

            <footer className={styles.footer}>
                <Footer/>
            </footer>

        </div>
    )
}