/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://oxeshomiijg2fdbdjnaoxybxwe.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v6cfwdlphvdx3fd5lb6nkugnay",
    "aws_cognito_identity_pool_id": "eu-central-1:07849312-fa31-4abb-881a-c83b10549be8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_wtUwEPASe",
    "aws_user_pools_web_client_id": "2orjvrt6257c30snric72c874s",
    "oauth": {},
    "aws_user_files_s3_bucket": "brandlogos124559-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
