/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://36bfdckwd5ceno2a4fimthur4e.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vrl47bto4berhhkwqj2qq7ya4y",
    "aws_cognito_identity_pool_id": "us-west-2:68efe620-85f2-4be4-a387-707ad41bfd24",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_qWu0wHba6",
    "aws_user_pools_web_client_id": "3rnh44839d7lgm00fujv3f9j80",
    "oauth": {},
    "aws_user_files_s3_bucket": "brandlogos63742-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
