import Head from 'next/head'
import {Divider, Container} from "@chakra-ui/layout";
import ServiceList from "../../components/Services/serviceList"
import {getAllServices} from "../../lib/services";
import {Input, Stack, useControllableState, Select} from "@chakra-ui/react";
import React from "react";
import {SearchIcon} from "@chakra-ui/icons";
import {getAllUzels} from "../../lib/uzels";

export default function Services({services = [], uzels = []}) {
    const [serviceName, setServiceName] = useControllableState({ defaultValue: "" })
    const [uzelId, setUzelId] = useControllableState({defaultValue: ""})

    return(
        <>
            <Head>
                <title>Service List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container mt={16} mb={4} maxW={"container.lg"}>
                <Stack isInline align={"center"}>
                    <SearchIcon/>
                    <Input
                        minHeight={10}
                        w={"full"}
                        variant={"unstyled"}
                        placeholder={"Поиск по услугам"}
                        value={serviceName}
                        onChange={(e) => {
                            setServiceName(e.target.value);
                        }}
                    />
                </Stack>
                <Divider my={4}/>
                <Stack isInline>
                    <Select
                        placeholder="Выберите узел"
                        onChange={(e) => setUzelId(e.target.value)}
                    >
                        <option value={"all"}>Все</option>
                        {uzels.map(uzel => (
                            <option key={uzel.id} value={uzel.id}>{uzel.name}</option>
                        ))}
                    </Select>
                </Stack>
                <Divider my={4}/>
                <ServiceList services={services} uzelId={uzelId} serviceName={serviceName} withPrice={true}/>
            </Container>
            <Divider/>
        </>
    )
}

export async function getStaticProps() {
    const serviceData = await getAllServices();
    const services = serviceData.map(service => {return service.params.service;})
    const uzelData = await getAllUzels();
    const uzels = uzelData.map(uzel => {return uzel.params.uzel;})

    return {
        props: {
            services,
            uzels,
        },
    };
}